- module: system
  metricsets:
    - core
    - cpu
    - load
    - diskio
    - filesystem
    - fsstat
    - memory
    - network
    - process
    - socket
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: true # FIXME Deprecated
  process.cgroups.enabled: true