cluster.name: "docker-cluster"
network.host: 0.0.0.0
transport.host: 0.0.0.0
bootstrap.memory_lock: true

node.name: cloud-service-master-node
node.master: true

xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true
xpack.graph.enabled: false
xpack.watcher.enabled: false
