# It will have to be changed to any went we go on AWS, those are Redhat server not Mac
# packetbeat.interfaces.device: en0 # For MAC only
# packetbeat.interfaces.device: any

packetbeat.flows:
  enabled: true
  timeout: 30s
  period: 10s

packetbeat.protocols:
  - type: icmp
    enabled: true

  - type: amqp
    enabled: true
    ports: [5672]

  - type: cassandra
    ports: [9042]

  - type: http
    enabled: true
    ports: [9200, 9600, 5601]

  - type: memcache
    ports: [11211]

logging.level: info

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["localhost:9200"]
    useranme: elastic # beats_system
    password: changeme

output.logstash:
  # all others beats use logstash, packetbeat use dns entry to find out but didn't work so localhost is a patch
  hosts: ["localhost:5044"]
  index: packetbeat

setup.kibana:
   host: "localhost:5601"
   protocol: "http"

logging.to_files: true
logging.files:
