#We monitor any devices on the host OS. For windows and OSX this is the VM hosting docker.
# see: https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-configuration.html
packetbeat.interfaces.device: en0

packetbeat.flows:
  enabled: true
  timeout: 30s
  period: 10s

packetbeat.protocols.icmp:
  enabled: true

packetbeat.protocols.dns:
  enabled: true
  ports: [53]
  include_authorities: true
  include_additionals: true

#We monitor any traffic to kibana, apache, ngnix and ES
packetbeat.protocols.http:
  enabled: true
  ports: [80, 8080, 8000, 5000, 8002]
  send_headers: true
  send_all_headers: true
  split_cookie: true
  send_request: false
  send_response: false
  transaction_timeout: 10s

output.logstash:
  hosts: ["127.0.0.1:5044"]
  worker: 1
  compression_level: 3
  index: packetbeat

logging.to_files: false
