version: '3.7'

services:

   elasticsearch:
      container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
      #environment:
      #  - http.host=0.0.0.0
      #  - bootstrap.memory_lock=true
      #  - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      ulimits:
       memlock:
          soft: -1
          hard: -1    
      volumes:
        - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
        - elastic-data:/usr/share/elasticsearch/data
      ports: ['9200:9200', '9300:9300']
      healthcheck:
        test: ["CMD", "curl","-s" ,"-f", "-u", "elastic:changeme", "http://localhost:9200/_cat/health"]
        interval: 60s
        timeout: 60s
        retries: 6
      networks: ['analytic_net']

   kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:6.4.3
      environment:
      #  ELASTICSEARCH_USERNAME: elastic 
        ELASTICSEARCH_PASSWORD: changeme
        ELASTICSEARCH_URL: http://elasticsearch:9200
        #SERVER_NAME: kibana.dmi.com
        #SERVER_HOST: "localhost"
        #XPATH_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
      volumes:
        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        - kibana-data:/usr/share/kibana/data
      ports: ['5601:5601']
      healthcheck:
        test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/login"]
        interval: 60s
        timeout: 60s
        retries: 6
      depends_on: ['elasticsearch']
      networks: ['analytic_net']


volumes:
  elastic-data:
    driver: local
  kibana-data:
    driver: local
  logstash-data:
    driver: local
  packetbeat-data:
    driver: local
  packetbeat-log:
    driver: local
    
networks: {analytic_net: {}}
