apm-server:
  # host: "0.0.0.0:8200"

setup.template.settings:
  index:
    number_of_shards: 1
    codec: best_compression

#============================== Deprecated: Kibana =====================================
setup.kibana:
   host: "http://kibana:5601"
   protocol: "http"

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
    useranme: elastic
    password: changeme

# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   enabled: true
#   useranme: elastic
#   password: changeme
  # indices:
  #   - index: "apm-%{[beat.version]}-sourcemap"
  #     when.contains:
  #       processor.event: "sourcemap"

  #   - index: "apm-%{[beat.version]}-error-%{+yyyy.MM.dd}"
  #     when.contains:
  #       processor.event: "error"

  #   - index: "apm-%{[beat.version]}-transaction-%{+yyyy.MM.dd}"
  #     when.contains:
  #       processor.event: "transaction"

  #   - index: "apm-%{[beat.version]}-span-%{+yyyy.MM.dd}"
  #     when.contains:
  #       processor.event: "span"

  #   - index: "apm-%{[beat.version]}-metric-%{+yyyy.MM.dd}"
  #     when.contains:
  #       processor.event: "metric"

  #   - index: "apm-%{[beat.version]}-onboarding-%{+yyyy.MM.dd}"
  #     when.contains:
  #       processor.event: "onboarding"

output.logstash:  # Boolean flag to enable or disable the output module.
  enabled: true
  hosts: ["logstash:5044"]
  index: 'apm'

logging.metrics.enabled: false
