apm-server:

setup.template.settings:
  index:
    number_of_shards: 1
    codec: best_compression

#============================== Deprecated: Kibana =====================================
setup.kibana:
   host: "http://kibana:5601"
   protocol: "http"

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
    useranme: elastic
    password: changeme

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
  index: 'apm'

logging.metrics.enabled: false
