cluster.name: "docker-cluster"
network.host: 0.0.0.0
transport.host: 0.0.0.0
node.name: service-node-1
http.port: 9200

#node.master: true

#transport.host: 127.0.0.1
#bootstrap.memory_lock: true

# path.data: /usr/share/elasticsearch/data
#xpack.security.enabled: false
#xpack.monitoring.enabled: true
#xpack.monitoring.collection.enabled: true
#xpack.graph.enabled: false
#xpack.watcher.enabled: false
