cluster.name: "docker-cluster"
network.host: 0.0.0.0
transport.host: 0.0.0.0
node.name: service-node-1

#node.master: true
#bootstrap.memory_lock: true

# path.data: /usr/share/elasticsearch/data
#xpack.security.enabled: false
#xpack.monitoring.enabled: true
#xpack.monitoring.collection.enabled: true
#xpack.graph.enabled: false
#xpack.watcher.enabled: false
