filebeat.registry_file: /usr/share/filebeat/data/registry
filebeat.config.prospectors:
  path: ${path.config}/prospectors.d/*.yml
  reload.enabled: false
filebeat.modules:
#Filebeat system module consumes logs from host OS through a mounted volume
- module: system
  syslog:
    var.paths: ["/var/log/host/system.log*"]

logging.level: info

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
    useranme: elastic
    password: changeme

output.logstash:
  hosts: ["localhost:5044"]
  index: filebeat

setup.kibana:
   host: "http://kibana:5601"
   protocol: "http"
