filebeat.config:
  inputs:
    enabled: true
    path: inputs.d/*.yml
    reload.enabled: true
    reload.period: 10s
  modules:
    enabled: true
    path: modules.d/*.yml
    reload.enabled: true
    reload.period: 10s

setup.dashboards.enabled: true
setup.dashboards.beat: 
setup.dashboards.kibana_index: .kibana
setup.dashboards.retry.enabled: true
setup.dashboards.retry.interval: 6s
setup.dashboards.retry.maximum: 0

logging.to_files: true
logging.files:
  name: filebeat
  path: /usr/share/filebeat/logs
  rotateeverybytes: 10485760
  keepfiles: 7

logging.level: debug

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
    useranme: elastic
    password: changeme

output.logstash:
  hosts: ["logstash:5044"]
  index: filebeat

setup.kibana:
   host: "http://kibana:5601"
   protocol: "http"