http.host: 0.0.0.0
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: changeme
xpack.monitoring.elasticsearch.url: https://elasticsearch:9200
xpack.monitoring.enabled: true
# xpack.monitoring.collection.enabled: true