server.host: "0"
server.name: "kibana"
elasticsearch.url: "http://elasticsearch:9200"
elasticsearch.username: elastic
elasticsearch.password: changeme
server.ssl.enabled: false
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.monitoring.enabled: true
xpack.reporting.encryptionKey: "OurSecretWillBeMuchMoreComplecated"