heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls: 
    - http://elasticsearch:9200
    - http://kibana:5601

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana

processors:
- add_cloud_metadata:

logging.level: info

setup.kibana:
  host: "http://kibana:5601"
  protocol: "http"

output.logstash:
  hosts: ["127.0.0.1:5044"]
