heartbeat.monitors:
- type: icmp
  schedule: '@every 5s'
  hosts: ["elasticsearch", "kibana"]
- type: tcp
  schedule: '@every 5s'
  hosts: ["elasticsearch:7", "kibana:7"]
  check.send: "Echo"
  check.receive: "Echo"
- type: http
  schedule: '@every 5s'
  urls: ["http://elasticsearch:9200", "http://kibana:5601"]
  check.response.status: 200

heartbeat.scheduler:
  limit: 10

logging.level: info
xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
    useranme: elastic
    password: changeme

output.logstash:
  hosts: ["logstash:5044"]
  index: hearbeat

setup.kibana:
   host: "http://kibana:5601"
   protocol: "http"
