metricbeat.config.modules:
  # As linux system auto update .modules.d sub directory.
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: true

#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]
output.logstash:
  hosts: ["127.0.0.1:5044"]
logging.to_files: false